services:
  - type: web
    name: iticket
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"