# Generated by Django 6.0.7 on 2026-08-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_place_id_event_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('building', models.CharField(max_length=300)),
                ('apparition', models.CharField(max_length=300)),
                ('email_index', models.CharField(max_length=155)),
                ('addintional_information', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='apps.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'apps_addresses',
            },
        ),
    ]
