# Generated by Django 6.0.7 on 2026-08-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_questions_is_visible_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesoutletstranslation',
            name='apps_sales_outlets_translation_uniq_lang',
        ),
        migrations.AlterField(
            model_name='salesoutlets',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salesoutlets',
            name='phone_number',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='salesoutlets',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='apps.place'),
        ),
        migrations.AlterField(
            model_name='salesoutlets',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='SalesOutletsTranslation',
        ),
    ]
